import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from './NavBar';
import ComingSoonPage from './comingsoon';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const { NODE_ENV } = process.env;
	return (
		<html lang="en">
			<body className={inter.className}>
				{NODE_ENV === 'development' ? (
					<ComingSoonPage />
				) : (
					<>
						<NavBar />
						<main>{children}</main>
					</>
				)}
			</body>
		</html>
	);
}
